### ISSUE TITLE
Not really an issue but a question: Celery

### ISSUE THREAD

**Issue by daddydrac** [ChristianKreuzberger/django_upgrade_video#2]
What is celery doing and what are its benefits for this use case?

**Comment by ChristianKreuzberger** [comment]
For this app it is doing literally nothing, as this was a demo (for a youtube video).

But other then that, they idea is to offload (long running) tasks (e.g., create a thumbnail image, create a PDF, ...) to one or multiple worker processes, which are running in the background.
