### ISSUE TITLE
running the prod version failed

### ISSUE THREAD

**Issue by faridos** [ChristianKreuzberger/django_upgrade_video#3]
the docker-compose fails to run the python service with prod.yml
exited with this error:
python_1    | Update user 'user'
python_1    | usermod: user root is currently used by process 1
python_1    | usermod: group 'user' does not exist
python_1    | Running command 'gunicorn -w 4 tickets.wsgi -b 0.0.0.0:8000'
python_1    | No passwd entry for user 'user'
django_upgrade_video_python_1 exited with code 1

**Comment by ChristianKreuzberger** [comment]
I've just pushed a change to the master branch that should fix this issue.
